apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::327878951135:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11SMWLZMBO2KB
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-01T16:19:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1482"
  uid: 4c15821a-71ac-4ba4-b68b-ec620e2619a5
